import { Link } from 'react-router-dom'
import { ArrowRight, Check, HeartHandshake, HeartPulse, Headphones, Home, LockKeyhole, ShieldCheck, UsersRound } from 'lucide-react'
import { LandingNavbar } from './LandingNavbar.jsx'

const values = [[ShieldCheck,'Verified Professionals'],[HeartHandshake,'Human-Centered Care'],[HeartPulse,'Family Connected'],[LockKeyhole,'Secure & Private']]
// Presentation-only metrics. Replace from one place when verified production figures exist.
const demoMetrics = [['1,000+','Families Trust Us','and growing every day'],['500+','Verified Professionals','doctors, nurses & caregivers'],['5K+','Home Visits','completed successfully'],['98%','Patient Satisfaction','based on family feedback'],['99.9%','Data Security','your privacy is our priority']]
const differences = [[Home,'Care at Home','Professional care delivered where your loved one feels most comfortable.'],[HeartPulse,'Real-Time Updates','Stay informed with live visit updates, medication reminders and alerts.'],[Headphones,'Dedicated Care Coordinator','One person who understands your family and manages the care journey.'],[LockKeyhole,'Secure & Private',"Your family's health information is protected with strong security."]]

export function AboutPage(){return <main className="ec-page ec-about-page"><LandingNavbar activePage="about"/><section className="ec-about-hero"><div><span>About EasyCare</span><h1>Care That Keeps<br/>Families <em>Connected</em></h1><p>EasyCare is a hybrid healthcare platform that brings trusted doctors, nurses and caregivers to your home or online — with a dedicated Care Coordinator and real-time visibility for your family.</p><div className="ec-about-values">{values.map(([Icon,title])=><article key={title}><i><Icon/></i><b>{title}</b></article>)}</div></div><div className="ec-about-photo"><img src="/easycare-home-care-hero.png" alt="EasyCare nurse connecting with an elderly patient"/><blockquote>“<br/>Our mission is simple:<br/><strong>Better care for them.</strong><br/>More peace of mind for you.<hr/><small>— The EasyCare Team</small></blockquote></div></section><section className="ec-about-content"><div className="ec-story"><h2>Our Story</h2><p>EasyCare was built in Mandalay with one purpose — to make quality healthcare more accessible, coordinated and transparent for elderly patients and their families.<br/>We understand the challenges families face when caring for aging loved ones, especially from afar.<br/>That’s why we combine professional care, thoughtful technology and human support to deliver seamless care experiences you can trust.</p></div><section className="ec-metrics" aria-label="EasyCare presentation metrics">{demoMetrics.map(([value,label,note],i)=><article key={label}><i>{i===0?<UsersRound/>:i===1?<ShieldCheck/>:i===2?<Home/>:i===3?<HeartHandshake/>:<LockKeyhole/>}</i><div><strong>{value}</strong><b>{label}</b><small>{note}</small></div></article>)}</section><h2 className="ec-difference-title">What Makes EasyCare Different</h2><section className="ec-differences">{differences.map(([Icon,title,text],i)=><article key={title}>{i===0&&<img src="/easycare-home-care-hero.png" alt="Care at home"/>}{i===2&&<img src="/easycare-care-coordinator.png" alt="Care coordinator"/>}<i><Icon/></i><div><h3>{title}</h3><p>{text}</p></div></article>)}</section><section className="ec-about-cta"><HeartHandshake/><div><h2>We are here for you and your family.</h2><p>Quality care. Transparent process. Peace of mind.</p></div><button className="ec-button ec-button-outline" type="button">Talk to Our Team</button><Link className="ec-button ec-button-primary" to="/doctors">Find Care Now <ArrowRight/></Link></section></section></main>}
