import { Link } from 'react-router-dom'
import { Activity, ArrowRight, Bell, CalendarDays, Check, Headphones, HeartHandshake, LockKeyhole, MessageSquare, Pill, ShieldCheck, UsersRound } from 'lucide-react'
import { LandingNavbar } from './LandingNavbar.jsx'

const trust=[[HeartHandshake,'Stay Connected'],[ShieldCheck,'Trusted Professionals'],[Bell,'Real-Time Updates'],[LockKeyhole,'Secure & Private']]
const capabilities=[[Activity,'Monitor Their Health','See visit updates, vital signs, medications and health trends in real time.'],[CalendarDays,'Upcoming Care & Appointments','Track upcoming visits, online consultations and medication schedules.'],[Pill,'Medications & Reminders','Stay informed about medications, reminders and adherence progress.'],[MessageSquare,'Communicate Easily','Message the Care Coordinator, care team or providers whenever you need.'],[ShieldCheck,'Secure & Permission-Based',"You see what’s important, respecting your loved one’s privacy and permissions."]]

function DemoPanel({index}){return <div className="ec-family-demo"><b>{index===0?'Health Overview':index===1?'Upcoming Visits':index===2?"Today’s Medications":index===3?'Care Messages':'Authorized Access'}</b>{index===0?<><span>Blood Pressure · 120/80</span><span>Blood Sugar · 142 mg/dL</span></>:index===1?<><span>May 27 · Home Visit</span><span>May 30 · Online Consultation</span></>:index===2?<><span>Amlodipine · 8:00 AM</span><span>Metformin · 12:00 PM</span></>:index===3?<><span>How was today’s visit?</span><span>Care update received ✓</span></>:<><span>Family Coordinator · Active</span><span>Permission-based access</span></>}</div>}
export function FamiliesPage(){return <main className="ec-page ec-families-page"><LandingNavbar activePage="families"/><section className="ec-families-hero"><div><span>For Families</span><h1>Peace of Mind for <strong>You.</strong><br/>Better Care for <em>Them.</em></h1><p>EasyCare helps you coordinate and monitor your loved one’s health and care — even when you’re far away.</p><div className="ec-family-trust">{trust.map(([Icon,title])=><article key={title}><i><Icon/></i><b>{title}</b></article>)}</div></div><div className="ec-families-photo"><img src="/easycare-care-coordinator.png" alt="Family member staying connected through EasyCare"/><blockquote>“<br/>I can’t always be there, but with EasyCare, I know my parents are in good hands.<hr/><small>Family member · Living abroad</small></blockquote></div></section><section className="ec-families-content"><header><h2>What You Can Do on EasyCare</h2><p>Everything you need to support your loved one’s health, all in one place.</p></header><section className="ec-capabilities">{capabilities.map(([Icon,title,text],i)=><article key={title}><div><i><Icon/></i><h3>{title}</h3></div><p>{text}</p><DemoPanel index={i}/></article>)}</section><section className="ec-never-alone"><HeartHandshake/><div><h2>You Are Never Alone in Their Care Journey</h2><p>Our Care Coordinators and care team work with you to ensure the best possible care for your family.</p><ul><li><Check/>Dedicated Care Coordinator</li><li><Check/>24/7 support for urgent needs</li><li><Check/>Verified healthcare professionals</li><li><Check/>Transparent care and pricing</li></ul></div><img src="/easycare-care-coordinator.png" alt="EasyCare care coordinator"/><aside><h3>Need Help or Have Questions?</h3><p>Our team is here to support you and your family.</p><button className="ec-button ec-button-primary" type="button"><MessageSquare/>Talk to Us</button></aside></section><section className="ec-family-security"><div><ShieldCheck/><span><b>Your family’s health is safe with us.</b><small>Quality care, transparency and peace of mind.</small></span></div><span>Licensed & Verified Professionals</span><span>Secure Data Protection</span><span>Transparent Pricing</span><span>Trusted by 1,000+ Families</span></section></section></main>}
