export const translations = {
  en: {
    languageName: 'English', portal: 'Patient portal', mobileNavigation: 'Mobile navigation', primaryNavigation: 'Primary navigation',
    nav: { dashboard: 'Dashboard', guardian: 'AI Health Guardian', doctors: 'Doctors', appointments: 'Appointments', carePlan: 'Care Plan', healthRecords: 'Health Records', prescriptions: 'Prescriptions', labResults: 'Lab Results', medications: 'Medications', subscription: 'Subscription', payments: 'Payments', messages: 'Messages', location: 'Location & SOS', settings: 'Settings', home: 'Home' },
    action: { viewDetails: 'View Details', bookAppointment: 'Book Appointment', callEmergency: 'Call Emergency', close: 'Close', save: 'Save', cancel: 'Cancel', logout: 'Logout / end session', reschedule: 'Reschedule', joinWaitingRoom: 'Join waiting room' },
    status: { all: 'All', upcoming: 'Upcoming', pending: 'Pending', confirmed: 'Confirmed', checked_in: 'Checked in', in_progress: 'In progress', completed: 'Completed', cancelled: 'Cancelled' },
    simulation: { generic: 'Synthetic presentation information — no real service is connected.', payment: 'Presentation Demo — No Real Payment', messages: 'Presentation messages are not delivered to a real doctor. No encryption claim is made.', location: 'No real dispatch or live location sharing is connected.', settings: 'Preference changes are local presentation state unless explicitly connected. Medical data cannot be edited here.' },
    guardian: { title: 'AI Health Guardian', subtitle: 'Deterministic presentation guidance—not medical assessment.', limitation: 'AI limitation: this deterministic demo cannot diagnose, prescribe, monitor, or replace a qualified clinician.', routineTitle: 'Routine guidance', routine: 'Your message does not match this demo’s emergency red flags. Book a clinician if symptoms persist or concern you.', urgentTitle: 'Prompt clinician review suggested', urgent: 'Arrange prompt clinical assessment. If symptoms become severe or an emergency warning sign appears, call emergency services.', emergencyTitle: 'Emergency warning signs', emergency: 'Your message matches an emergency red flag. Call local emergency services now. Do not wait for a routine appointment.', unavailableTitle: 'Guardian unavailable', unavailable: 'The presentation assistant is unavailable and cannot assess symptoms. Contact a qualified clinician, or emergency services for urgent warning signs.', override: 'Emergency red flags override routine booking.' },
    appointment: { title: 'Appointments', details: 'Appointment Details', loading: 'Loading appointments…', notFound: 'Appointment not found', noAccess: 'It may not exist or you may not have access to it.', manage: 'Manage your upcoming and past appointments.', booked: 'Appointment booked', rescheduled: 'Appointment rescheduled', cancelled: 'Appointment cancelled', updated: 'Status updated', rescheduledSuccess: 'Appointment rescheduled successfully. Dashboard and appointment details now show the new time.', cancelledSuccess: 'Appointment cancelled. The appointment time has been released safely.', noAppointments: 'No appointments here', findDoctor: 'Find a doctor' },
    settings: { title: 'Settings', subtitle: 'Safe account and presentation preferences.', profile: 'Profile information', displayName: 'Display name', email: 'Email', noMedical: 'No medical fields or records can be edited.', editProfile: 'Edit profile', saveProfile: 'Save presentation changes', saved: 'Presentation profile saved locally.', preferences: 'Preferences', language: 'Language', appearance: 'Appearance', light: 'Light', system: 'System', notifications: 'Presentation notifications' },
    validation: { required: 'This field is required.', validFutureDate: 'Choose a valid future date.', chooseAvailableTime: 'Choose an available time.' },
  },
  my: {
    languageName: 'မြန်မာ', portal: 'လူနာ ပေါ်တယ်', mobileNavigation: 'မိုဘိုင်း လမ်းညွှန်', primaryNavigation: 'အဓိက လမ်းညွှန်',
    nav: { dashboard: 'ပင်မစာမျက်နှာ', guardian: 'AI ကျန်းမာရေးစောင့်ရှောက်သူ', doctors: 'ဆရာဝန်များ', appointments: 'ချိန်းဆိုမှုများ', healthRecords: 'ကျန်းမာရေးမှတ်တမ်းများ', prescriptions: 'ဆေးညွှန်းများ', labResults: 'ဓာတ်ခွဲရလဒ်များ', medications: 'ဆေးဝါးများ', subscription: 'စာရင်းသွင်းမှု', payments: 'ငွေပေးချေမှုများ', messages: 'မက်ဆေ့ချ်များ', location: 'တည်နေရာနှင့် SOS', settings: 'ဆက်တင်များ', home: 'ပင်မ' },
    action: { viewDetails: 'အသေးစိတ်ကြည့်ရန်', bookAppointment: 'ချိန်းဆိုရန်', callEmergency: 'အရေးပေါ် ဖုန်းခေါ်ရန်', close: 'ပိတ်ရန်', save: 'သိမ်းရန်', cancel: 'ပယ်ဖျက်ရန်', logout: 'အကောင့်မှ ထွက်ရန်', reschedule: 'အချိန်ပြောင်းရန်', joinWaitingRoom: 'စောင့်ဆိုင်းခန်း ဝင်ရန်' },
    status: { all: 'အားလုံး', upcoming: 'လာမည့်', pending: 'စောင့်ဆိုင်းဆဲ', confirmed: 'အတည်ပြုပြီး', checked_in: 'ရောက်ရှိစာရင်းသွင်းပြီး', in_progress: 'ဆောင်ရွက်ဆဲ', completed: 'ပြီးဆုံးပြီး', cancelled: 'ပယ်ဖျက်ပြီး' },
    simulation: { generic: 'တင်ဆက်မှုအတွက် ဖန်တီးထားသော အချက်အလက်သာ ဖြစ်ပြီး တကယ့်ဝန်ဆောင်မှု မချိတ်ဆက်ထားပါ။', payment: 'တင်ဆက်မှု သရုပ်ပြ — တကယ့်ငွေပေးချေမှု မရှိပါ', messages: 'တင်ဆက်မှု မက်ဆေ့ချ်များကို တကယ့်ဆရာဝန်ထံ မပို့ပါ။ ကုဒ်ဖြင့်လုံခြုံမှုရှိသည်ဟု မဆိုထားပါ။', location: 'တကယ့်အရေးပေါ်အဖွဲ့ စေလွှတ်မှု သို့မဟုတ် တိုက်ရိုက်တည်နေရာ မျှဝေမှု မချိတ်ဆက်ထားပါ။', settings: 'ရွေးချယ်မှုများသည် တင်ဆက်မှုအတွင်းသာ ဖြစ်သည်။ ဆေးဘက်ဆိုင်ရာအချက်အလက်များကို ဤနေရာတွင် မပြင်နိုင်ပါ။' },
    guardian: { title: 'AI ကျန်းမာရေးစောင့်ရှောက်သူ', subtitle: 'ကြိုတင်သတ်မှတ်ထားသော တင်ဆက်မှုလမ်းညွှန်သာ ဖြစ်ပြီး ဆေးဘက်ဆိုင်ရာ စစ်ဆေးမှုမဟုတ်ပါ။', limitation: 'AI ကန့်သတ်ချက် — ဤသရုပ်ပြစနစ်သည် ရောဂါရှာဖွေခြင်း၊ ဆေးညွှန်းပေးခြင်း၊ စောင့်ကြည့်ခြင်း မပြုနိုင်သလို အရည်အချင်းပြည့် ဆရာဝန်ကို အစားမထိုးနိုင်ပါ။', routineTitle: 'ပုံမှန် လမ်းညွှန်ချက်', routine: 'သင့်စာသည် ဤသရုပ်ပြစနစ်၏ အရေးပေါ်လက္ခဏာများနှင့် မကိုက်ညီပါ။ လက္ခဏာများ ဆက်ရှိနေပါက ဆရာဝန်နှင့် ချိန်းဆိုပါ။', urgentTitle: 'ဆရာဝန်နှင့် အမြန်တိုင်ပင်ရန် အကြံပြုသည်', urgent: 'ဆရာဝန်၏ စစ်ဆေးမှုကို အမြန်ရယူပါ။ လက္ခဏာပြင်းထန်လာပါက အရေးပေါ်ဝန်ဆောင်မှုကို ဖုန်းခေါ်ပါ။', emergencyTitle: 'အရေးပေါ် သတိပေးလက္ခဏာများ', emergency: 'သင့်စာသည် အရေးပေါ်လက္ခဏာနှင့် ကိုက်ညီပါသည်။ ဒေသဆိုင်ရာ အရေးပေါ်ဝန်ဆောင်မှုကို ယခုချက်ချင်း ဖုန်းခေါ်ပါ။ ပုံမှန်ချိန်းဆိုမှုကို မစောင့်ပါနှင့်။', unavailableTitle: 'AI စောင့်ရှောက်သူ အသုံးမပြုနိုင်ပါ', unavailable: 'တင်ဆက်မှုအကူစနစ် အသုံးမပြုနိုင်သဖြင့် လက္ခဏာများကို မစစ်ဆေးနိုင်ပါ။ ဆရာဝန် သို့မဟုတ် အရေးပေါ်ဝန်ဆောင်မှုကို ဆက်သွယ်ပါ။', override: 'အရေးပေါ်လက္ခဏာများသည် ပုံမှန်ချိန်းဆိုမှုထက် ဦးစားပေးပါသည်။' },
    appointment: { title: 'ချိန်းဆိုမှုများ', details: 'ချိန်းဆိုမှု အသေးစိတ်', loading: 'ချိန်းဆိုမှုများ ဖွင့်နေသည်…', notFound: 'ချိန်းဆိုမှု မတွေ့ပါ', noAccess: 'ချိန်းဆိုမှု မရှိခြင်း သို့မဟုတ် သင်ကြည့်ခွင့်မရှိခြင်း ဖြစ်နိုင်သည်။', manage: 'လာမည့်နှင့် ယခင်ချိန်းဆိုမှုများကို စီမံပါ။', booked: 'ချိန်းဆိုပြီး', rescheduled: 'ချိန်းဆိုချိန် ပြောင်းပြီး', cancelled: 'ချိန်းဆိုမှု ပယ်ဖျက်ပြီး', updated: 'အခြေအနေ ပြောင်းလဲပြီး', rescheduledSuccess: 'ချိန်းဆိုချိန် အောင်မြင်စွာ ပြောင်းပြီးပါပြီ။ ပင်မစာမျက်နှာနှင့် အသေးစိတ်တွင် အချိန်အသစ်ကို ပြသထားသည်။', cancelledSuccess: 'ချိန်းဆိုမှု ပယ်ဖျက်ပြီး အချိန်ကို လုံခြုံစွာ ပြန်လွှတ်ပြီးပါပြီ။', noAppointments: 'ဤနေရာတွင် ချိန်းဆိုမှု မရှိပါ', findDoctor: 'ဆရာဝန်ရှာရန်' },
    settings: { title: 'ဆက်တင်များ', subtitle: 'လုံခြုံသော အကောင့်နှင့် တင်ဆက်မှုရွေးချယ်မှုများ။', profile: 'ကိုယ်ရေးအချက်အလက်', displayName: 'ပြသမည့်အမည်', email: 'အီးမေးလ်', noMedical: 'ဆေးဘက်ဆိုင်ရာအကွက်များနှင့် မှတ်တမ်းများကို မပြင်နိုင်ပါ။', editProfile: 'ကိုယ်ရေးအချက်အလက် ပြင်ရန်', saveProfile: 'တင်ဆက်မှုအပြောင်းအလဲ သိမ်းရန်', saved: 'တင်ဆက်မှု ကိုယ်ရေးအချက်အလက်ကို ဤစက်ရှင်အတွင်း သိမ်းပြီးပါပြီ။', preferences: 'ရွေးချယ်မှုများ', language: 'ဘာသာစကား', appearance: 'အသွင်အပြင်', light: 'အလင်း', system: 'စနစ်အတိုင်း', notifications: 'တင်ဆက်မှု အသိပေးချက်များ' },
    validation: { required: 'ဤအကွက်ကို ဖြည့်ရန်လိုသည်။', validFutureDate: 'မှန်ကန်သော အနာဂတ်ရက်စွဲကို ရွေးပါ။', chooseAvailableTime: 'ရရှိနိုင်သောအချိန်ကို ရွေးပါ။' },
  },
}

translations.my.nav.carePlan = 'စောင့်ရှောက်မှုအစီအစဉ်'

export function getTranslation(dictionary, key) {
  return key.split('.').reduce((value, part) => value?.[part], dictionary)
}
