begin;
create type public.catalog_service_type as enum ('teleconsultation','home_visit','nursing','caregiver');
create table public.service_catalog (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, provider_type public.provider_type, service_type public.catalog_service_type not null, base_price numeric(12,2) not null check(base_price>=0), currency char(3) not null default 'MMK', active boolean not null default true);
create table public.pricing_rules (id uuid primary key default gen_random_uuid(), service_id uuid references public.service_catalog(id) on delete restrict, rule_type public.pricing_rule_type not null, provider_type public.provider_type, value_type public.pricing_value_type not null, value numeric not null check(value>=0), effective_from timestamptz, effective_to timestamptz, active boolean not null default true, check(effective_to is null or effective_from is null or effective_to>=effective_from), check(value_type<>'percentage' or value<=100));
create table public.care_packages (id uuid primary key default gen_random_uuid(), name text not null, price numeric(12,2) check(price is null or price>=0), billing_period public.billing_period, active boolean not null default true);
create table public.package_services (package_id uuid not null references public.care_packages(id) on delete restrict, service_id uuid not null references public.service_catalog(id) on delete restrict, included_quantity integer check(included_quantity is null or included_quantity>0), primary key(package_id,service_id));
create table public.subscriptions (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.patients(id) on delete restrict, purchased_by_profile_id uuid not null references public.profiles(id) on delete restrict, package_id uuid not null references public.care_packages(id) on delete restrict, status public.subscription_status not null default 'pending', start_at timestamptz, end_at timestamptz, renewal_type public.renewal_type, created_at timestamptz not null default statement_timestamp(), check(end_at is null or start_at is null or end_at>=start_at));
create table public.payments (id uuid primary key default gen_random_uuid(), payer_profile_id uuid not null references public.profiles(id) on delete restrict, patient_id uuid not null references public.patients(id) on delete restrict, appointment_id uuid references public.appointments(id) on delete restrict, subscription_id uuid references public.subscriptions(id) on delete restrict, amount numeric(12,2) not null check(amount>=0), currency char(3) not null default 'MMK', status public.payment_status not null default 'pending', payment_method text, transaction_reference text unique, paid_at timestamptz, refunded_at timestamptz, created_at timestamptz not null default statement_timestamp(), check(appointment_id is not null or subscription_id is not null));
commit;
